# Generated by Django 5.1.5 on 2025-02-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createuser',
            old_name='name',
            new_name='username',
        ),
    ]
