# Generated by Django 5.1.5 on 2025-02-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0002_rename_name_createuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
