# Generated by Django 5.1.5 on 2025-02-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0003_alter_createuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
