# Generated by Django 5.1.5 on 2025-02-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0005_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='username',
            field=models.CharField(default='default_username', max_length=20, unique=True),
        ),
    ]
