# Generated by Django 5.1.5 on 2025-02-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0006_plan_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
