# Generated by Django 5.1.5 on 2025-02-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0008_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, unique=True, verbose_name='Группа крови')),
                ('color', models.CharField(default='#E53935', max_length=50, verbose_name='Цвет')),
            ],
        ),
        migrations.AddField(
            model_name='createuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
