# Generated by Django 5.1.5 on 2025-02-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0011_createuser_groups_createuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Группа крови'),
        ),
    ]
