# Generated by Django 5.1.5 on 2025-02-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0012_alter_bloodgroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
