# Generated by Django 5.1.5 on 2025-02-18 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0013_createuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='group_of_blood',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='0+', max_length=10),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=20)),
                ('time', models.CharField(default='8:30')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.plan', to_field='username')),
            ],
        ),
    ]
