# Generated by Django 5.1.5 on 2025-02-18 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0014_alter_plan_group_of_blood_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datamodel', to='medicine_app.plan', to_field='username'),
        ),
    ]
